// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNG57ygUwVzgzXkUWV54tk3MyT2m4PAfA',
    appId: '1:489226590719:web:78190310b35e73a6c52fca',
    messagingSenderId: '489226590719',
    projectId: 'flutterapp-649f8',
    authDomain: 'flutterapp-649f8.firebaseapp.com',
    storageBucket: 'flutterapp-649f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-DrU-DotyX46JU_7XzSV2QAVP4gcdsc',
    appId: '1:489226590719:android:7a66d3139a28846ac52fca',
    messagingSenderId: '489226590719',
    projectId: 'flutterapp-649f8',
    storageBucket: 'flutterapp-649f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZA6lvYGSYOB6c_Z7JcU-9NIyw7oMc8Us',
    appId: '1:489226590719:ios:98bd32252d089ceac52fca',
    messagingSenderId: '489226590719',
    projectId: 'flutterapp-649f8',
    storageBucket: 'flutterapp-649f8.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
